// Generated by gencpp from file turtlebot3_msgs/CheckStatusResponse.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_MSGS_MESSAGE_CHECKSTATUSRESPONSE_H
#define TURTLEBOT3_MSGS_MESSAGE_CHECKSTATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot3_msgs
{
template <class ContainerAllocator>
struct CheckStatusResponse_
{
  typedef CheckStatusResponse_<ContainerAllocator> Type;

  CheckStatusResponse_()
    : success(false)  {
    }
  CheckStatusResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CheckStatusResponse_

typedef ::turtlebot3_msgs::CheckStatusResponse_<std::allocator<void> > CheckStatusResponse;

typedef boost::shared_ptr< ::turtlebot3_msgs::CheckStatusResponse > CheckStatusResponsePtr;
typedef boost::shared_ptr< ::turtlebot3_msgs::CheckStatusResponse const> CheckStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator1> & lhs, const ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator1> & lhs, const ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_msgs/CheckStatusResponse";
  }

  static const char* value(const ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot3_msgs::CheckStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_MSGS_MESSAGE_CHECKSTATUSRESPONSE_H
