// Generated by gencpp from file turtlebot3_msgs/CheckStatusRequest.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_MSGS_MESSAGE_CHECKSTATUSREQUEST_H
#define TURTLEBOT3_MSGS_MESSAGE_CHECKSTATUSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot3_msgs
{
template <class ContainerAllocator>
struct CheckStatusRequest_
{
  typedef CheckStatusRequest_<ContainerAllocator> Type;

  CheckStatusRequest_()
    : robotID()
    , request()  {
    }
  CheckStatusRequest_(const ContainerAllocator& _alloc)
    : robotID(_alloc)
    , request(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robotID_type;
  _robotID_type robotID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CheckStatusRequest_

typedef ::turtlebot3_msgs::CheckStatusRequest_<std::allocator<void> > CheckStatusRequest;

typedef boost::shared_ptr< ::turtlebot3_msgs::CheckStatusRequest > CheckStatusRequestPtr;
typedef boost::shared_ptr< ::turtlebot3_msgs::CheckStatusRequest const> CheckStatusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator1> & lhs, const ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator2> & rhs)
{
  return lhs.robotID == rhs.robotID &&
    lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator1> & lhs, const ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "865aadf2c6758ad512f11b5ca5adcef1";
  }

  static const char* value(const ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x865aadf2c6758ad5ULL;
  static const uint64_t static_value2 = 0x12f11b5ca5adcef1ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_msgs/CheckStatusRequest";
  }

  static const char* value(const ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string robotID\n"
"string request\n"
;
  }

  static const char* value(const ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robotID);
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckStatusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot3_msgs::CheckStatusRequest_<ContainerAllocator>& v)
  {
    s << indent << "robotID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robotID);
    s << indent << "request: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_MSGS_MESSAGE_CHECKSTATUSREQUEST_H
