// Generated by gencpp from file turtlebot3_msgs/CheckStatus.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_MSGS_MESSAGE_CHECKSTATUS_H
#define TURTLEBOT3_MSGS_MESSAGE_CHECKSTATUS_H

#include <ros/service_traits.h>


#include <turtlebot3_msgs/CheckStatusRequest.h>
#include <turtlebot3_msgs/CheckStatusResponse.h>


namespace turtlebot3_msgs
{

struct CheckStatus
{

typedef CheckStatusRequest Request;
typedef CheckStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckStatus
} // namespace turtlebot3_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlebot3_msgs::CheckStatus > {
  static const char* value()
  {
    return "7ff597cbc0b70e34c1edffaf7514d72b";
  }

  static const char* value(const ::turtlebot3_msgs::CheckStatus&) { return value(); }
};

template<>
struct DataType< ::turtlebot3_msgs::CheckStatus > {
  static const char* value()
  {
    return "turtlebot3_msgs/CheckStatus";
  }

  static const char* value(const ::turtlebot3_msgs::CheckStatus&) { return value(); }
};


// service_traits::MD5Sum< ::turtlebot3_msgs::CheckStatusRequest> should match
// service_traits::MD5Sum< ::turtlebot3_msgs::CheckStatus >
template<>
struct MD5Sum< ::turtlebot3_msgs::CheckStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot3_msgs::CheckStatus >::value();
  }
  static const char* value(const ::turtlebot3_msgs::CheckStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot3_msgs::CheckStatusRequest> should match
// service_traits::DataType< ::turtlebot3_msgs::CheckStatus >
template<>
struct DataType< ::turtlebot3_msgs::CheckStatusRequest>
{
  static const char* value()
  {
    return DataType< ::turtlebot3_msgs::CheckStatus >::value();
  }
  static const char* value(const ::turtlebot3_msgs::CheckStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlebot3_msgs::CheckStatusResponse> should match
// service_traits::MD5Sum< ::turtlebot3_msgs::CheckStatus >
template<>
struct MD5Sum< ::turtlebot3_msgs::CheckStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot3_msgs::CheckStatus >::value();
  }
  static const char* value(const ::turtlebot3_msgs::CheckStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot3_msgs::CheckStatusResponse> should match
// service_traits::DataType< ::turtlebot3_msgs::CheckStatus >
template<>
struct DataType< ::turtlebot3_msgs::CheckStatusResponse>
{
  static const char* value()
  {
    return DataType< ::turtlebot3_msgs::CheckStatus >::value();
  }
  static const char* value(const ::turtlebot3_msgs::CheckStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLEBOT3_MSGS_MESSAGE_CHECKSTATUS_H
